name: Hypervisor

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-1 cargo +nightly xbuild --target x86_64-unknown-uefi --verbose
