name: Mythril

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-4 make fmt
  test:
    runs-on: ubuntu-18.04
    needs: fmt
    steps:
    - uses: actions/checkout@v1
    - name: Unit Tests
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-4 make test
  build:
    runs-on: ubuntu-18.04
    needs: fmt
    steps:
    - uses: actions/checkout@v1
    - name: Multiboot2 Image Build
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-4 make multiboot2
