name: Hypervisor

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-2 make fmt
    - name: Unit Tests
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-2 make test
    - name: EFI Image Build
      run: docker run -v $GITHUB_WORKSPACE:/src adamschwalm/hypervisor-build:docker-2 make efi
