name: Mythril

on: [push]

jobs:
  fmt:
    container: adamschwalm/hypervisor-build:docker-2
    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: make fmt
  test:
    container: adamschwalm/hypervisor-build:docker-2
    needs: fmt
    steps:
    - uses: actions/checkout@v1
    - name: Unit Tests
      run: make test
  build:
    container: adamschwalm/hypervisor-build:docker-2
    needs: fmt
    steps:
    - uses: actions/checkout@v1
    - name: EFI Image Build
      run: make efi
